services:
  rabbitmq:
    image: rabbitmq:4.2.3-management
    ports:
      - 5672:5672 # rabbitmq port
      - 15672:15672 # app management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
