/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.rabbitmq.stream.*;

public class ConsumerManualTrackingApplication {

    public static void main(String[] args) {
        Environment environment = Environment
                .builder()
                .uri("rabbitmq-stream://admin:admin@rabbitmq-node1:5552")
                .build();

        environment.streamCreator()
                .stream("test-stream")
                .create();

        // 1. Controle manual sem o rabbitmq. Db cache, arquivo...
        // 2. Control manual COM o Rabbitmq

        // consumer - modelo pull
        Consumer consumer = environment.consumerBuilder()
                .stream("test-stream")
                .manualTrackingStrategy()
                .builder()
                // .noTrackingStrategy()
                // .subscriptionListener(subscription -> {
                // // long offset = getOffsetFromDatabase("consumer-manual-tracking"); //
                // Recupera
                // // o offset do banco de dados

                // // subscription.offsetSpecification().getOffset(); // offset atual do
                // consumidor

                // // se não tiver offset, usar OffsetSpecification.first() ou
                // // OffsetSpecification.last()

                // // subscription.offsetSpecification(OffsetSpecification.offset(offset));
                // // Define o offset para o
                // // consumidor
                // })
                .name("consumer-auto-tracking")
                .messageHandler((offset, message) -> {
                    System.out.println("Received message: " + new String(message.getBodyAsBinary()));
                    System.out.println("Message offset: " + offset.offset());

                    // if (contition) {
                    // condicoes = numero de offsets lidos, evento específico, etc
                    // storeMyDatabase("consumer-manual-tracking", offset.offset()); // Armazena o
                    // offset no banco de dados
                    // }

                    if (offset.offset() % 2 == 0) { // Exemplo: armazena o offset a cada 10 mensagens
                        System.out.println("Storing offset: " + offset.offset());
                        // storeMyDatabase("consumer-manual-tracking", offset.offset()); // Armazena o
                        // offset no banco de dados
                        offset.storeOffset();
                    }

                })
                .build();

        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            try {
                System.out.println("Shutting down consumer...");
                consumer.close();
                environment.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }));
    }
}
