/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;

import com.rabbitmq.stream.*;

public class ConsumerApplication {
    public static void main(String[] args) {
        Environment environment = Environment
                .builder()
                .uri("rabbitmq-stream://admin:admin@rabbitmq-node1:5552")
                .build();

        environment.streamCreator()
                .stream("test-stream")
                .create();

        // consumer - modelo pull
        Consumer consumer = environment.consumerBuilder()
                .offset(OffsetSpecification.first())
                // .stream("test-stream") //É trabalho do consumidor guardar o offset para
                // indicar a partir de onde ele quer consumir as mensagens
                .messageHandler((offset, message) -> {
                    System.out.println("Received message: " + new String(message.getBodyAsBinary()));
                    System.out.println("Message offset: " + offset.offset());
                })
                .build();

        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            try {
                System.out.println("Shutting down consumer...");
                consumer.close();
                environment.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }));

        System.out.println("Message sent to RabbitMQ Stream!");
    }
}
