/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;

import com.rabbitmq.stream.*;

public class ProducerApplication {
    public static void main(String[] args) throws Exception {
        Environment environment = Environment
                .builder()
                .uri("rabbitmq-stream://admin:admin@rabbitmq-node1:5552")
                .build();

        // assert/declaracao da fila
        environment.streamCreator()
                .stream("test-stream")
                .create();

        Producer producer = environment.producerBuilder()
                .stream("test-stream")
                .build();

        Message message = producer.messageBuilder()
                .addData("Hello, RabbitMQ Stream!".getBytes())
                .build();

        CountDownLatch publishConfirmLatch = new CountDownLatch(1);

        // send message
        producer.send(message, confirmStatus -> {
            if (confirmStatus.isConfirmed()) {
                System.out.println("Message acknowledged by RabbitMQ Stream.");
            } else {
                System.out.println("Message not acknowledged by RabbitMQ Stream.");
            }

            publishConfirmLatch.countDown();
        });

        publishConfirmLatch.await(10, TimeUnit.SECONDS);

        producer.close();
        environment.close();

        System.out.println("Message sent to RabbitMQ Stream!");
    }
}
