/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;
import java.util.stream.IntStream;

import com.rabbitmq.stream.*;

public class ProducerBatchApplication {
    public static void main(String[] args) throws Exception {
        Environment environment = Environment
                .builder()
                .uri("rabbitmq-stream://admin:admin@rabbitmq-node1:5552")
                .build();

        // assert/declaracao da fila
        environment.streamCreator()
                .stream("test-stream")
                .argument("max-length-bytes", "100000000") // Define o tamanho áximo da stream
                .argument("max-age", "7D") // politica de retenção de mensagens, nesse caso 7 dias
                .argument("initial-cluster-size", "3") // define o tamanho do cluster
                .argument("queue-leader-locator", "balanced") // define a politica de distribuição de mensagens entre os
                                                              // nós do cluster
                .argument("stream-max-segment-size-bytes", "100000000") // define o tamanho máximo de cada segmento da
                                                                        // stream, nesse caso 100MB, padrão é 512MB
                .create();

        Producer producer = environment.producerBuilder()
                .stream("test-stream")
                .build();

        int messageCount = 10;

        CountDownLatch publishConfirmLatch = new CountDownLatch(1);

        IntStream.range(0, messageCount).forEach(i -> {
            Message message = producer.messageBuilder()
                    .addData(("Hello, Sending message " + i + "!!").getBytes())
                    .build();

            // send message
            producer.send(message, confirmStatus -> {
                if (confirmStatus.isConfirmed()) {
                    System.out.println("Message acknowledged by RabbitMQ Stream.");
                } else {
                    System.out.println("Message not acknowledged by RabbitMQ Stream.");
                }

                publishConfirmLatch.countDown();
            });

        });

        publishConfirmLatch.await(10, TimeUnit.SECONDS);

        producer.close();
        environment.close();

        System.out.println("Message sent to RabbitMQ Stream!");
    }
}
