/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.rabbitmq.stream.*;

public class SuperConsumerApplication {
    public static void main(String[] args) throws Exception {
        Environment environment = Environment
                .builder()
                .uri("rabbitmq-stream://admin:admin@rabbitmq-node1:5552")
                .build();

        // assert/declaracao da fila
        environment.streamCreator()
                .stream("test-super-stream")
                .superStream()
                // .partitions(3)
                .bindingKeys("a", "b", "c")
                .creator()
                .create();

        Consumer consumer = environment.consumerBuilder()
                .superStream("test-super-stream")
                .name("test-super-consumer-nfe")
                .singleActiveConsumer() // cria produces para cada stream
                // .singleActiveConsumer()
                .offset(OffsetSpecification.first())
                .messageHandler((offset, message) -> {
                    System.out.println("Received message: " + new String(message.getBodyAsBinary()));
                    System.out.println("Message offset: " + offset.offset());
                })
                .build();

        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            try {
                System.out.println("Shutting down consumer...");
                consumer.close();
                environment.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }));
    }
}
